"""Move use_alter FKs out of op.create_table into explicit op.create_foreign_key calls."""
import glob
import os
import re

_versions = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "alembic", "versions", "*.py")
path = sorted(glob.glob(_versions), key=os.path.getmtime)[-1]  # newest migration
src = open(path, encoding="utf-8").read()
lines = src.splitlines()

out = []
fks = []  # (name, table, local_cols, remote_table, remote_cols, ondelete)
current_table = None
for line in lines:
    m = re.match(r"\s*op\.create_table\('(\w+)'", line)
    if m:
        current_table = m.group(1)
    fk = re.match(
        r"\s*sa\.ForeignKeyConstraint\(\[(.*?)\], \[(.*?)\], name='(\w+)'(?:, ondelete='(\w+ ?\w*)')?, use_alter=True\),?",
        line,
    )
    if fk and current_table:
        local = [c.strip().strip("'") for c in fk.group(1).split(",")]
        remote = [c.strip().strip("'") for c in fk.group(2).split(",")]
        remote_table = remote[0].split(".")[0]
        remote_cols = [c.split(".")[1] for c in remote]
        fks.append((fk.group(3), current_table, local, remote_table, remote_cols, fk.group(4)))
        continue  # drop the inline line
    out.append(line)

text = "\n".join(out)

create_calls = "\n".join(
    f"    op.create_foreign_key('{name}', '{table}', '{rtable}', {local!r}, {rcols!r}"
    + (f", ondelete='{ond}'" if ond else "")
    + ")"
    for name, table, local, rtable, rcols, ond in fks
)
drop_calls = "\n".join(
    f"    op.drop_constraint('{name}', '{table}', type_='foreignkey')" for name, table, *_ in fks
)

# insert create calls before the end-of-upgrade marker; drops at start of downgrade
text = text.replace(
    "    # ### end Alembic commands ###\n\n\ndef downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n",
    "    # deferred (cyclic) foreign keys\n" + create_calls + "\n    # ### end Alembic commands ###\n\n\n"
    "def downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n" + drop_calls + "\n",
    1,
)
open(path, "w", encoding="utf-8").write(text)
print(f"moved {len(fks)} FKs; file {path}")
