"""initial schema

Revision ID: 141b25b0a67a
Revises: 
Create Date: 2026-08-16 21:25:49.862214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '141b25b0a67a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('name', name=op.f('uq_appointments_name'))
    )
    op.create_table('brands',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('code', name=op.f('uq_brands_code'))
    )
    op.create_table('countries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('gmt', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('divisions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions')),
    sa.UniqueConstraint('name', name=op.f('uq_divisions_name'))
    )
    op.create_table('fiscal_years',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_years')),
    sa.UniqueConstraint('name', name=op.f('uq_fiscal_years_name'))
    )
    op.create_table('item_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_item_categories_code'))
    )
    op.create_table('item_units',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_units')),
    sa.UniqueConstraint('code', name=op.f('uq_item_units_code'))
    )
    op.create_table('modules',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules')),
    sa.UniqueConstraint('code', name=op.f('uq_modules_code'))
    )
    op.create_table('procurement_items',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('grn_no', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imc', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('deno', sa.String(length=50), nullable=True),
    sa.Column('receive_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('part_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_items')),
    sa.UniqueConstraint('external_id', name=op.f('uq_procurement_items_external_id'))
    )
    op.create_index(op.f('ix_procurement_items_grn_no'), 'procurement_items', ['grn_no'], unique=False)
    op.create_table('ranks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('name', name=op.f('uq_ranks_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('ship_base_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ship_base_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_ship_base_categories_code'))
    )
    op.create_table('stores',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('store_type', sa.String(length=50), nullable=True),
    sa.Column('concern', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('code', name=op.f('uq_stores_code'))
    )
    op.create_table('users',
    sa.Column('user_type', sa.Enum('super_admin', 'admin', 'office_user', 'ship_base_user', name='user_type'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('office_id', sa.BigInteger(), nullable=True),
    sa.Column('ship_base_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('districts',
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_districts_division_id_divisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('division_id', 'name', name='uq_districts_division_name')
    )
    op.create_table('item_models',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_item_models_brand_id_brands'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_models')),
    sa.UniqueConstraint('code', name=op.f('uq_item_models_code'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('can_menu', sa.Boolean(), nullable=False),
    sa.Column('can_list', sa.Boolean(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_add', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_role_permissions_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_permissions_role_module')
    )
    op.create_table('ship_bases',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('ship', 'base', name='ship_base_type'), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ship_base_categories.id'], name=op.f('fk_ship_bases_category_id_ship_base_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ship_bases')),
    sa.UniqueConstraint('code', name=op.f('uq_ship_bases_code'))
    )
    op.create_table('items',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('oem', sa.String(length=200), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('country_of_manufacture_id', sa.BigInteger(), nullable=True),
    sa.Column('country_of_origin_id', sa.BigInteger(), nullable=True),
    sa.Column('procurement_year', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('local_supplier', sa.String(length=200), nullable=True),
    sa.Column('principal', sa.String(length=200), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('functional_status', sa.Enum('operational', 'non_operational', 'defect', 'survey', 'obsolete', name='functional_status'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_items_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], name=op.f('fk_items_category_id_item_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_of_manufacture_id'], ['countries.id'], name=op.f('fk_items_country_of_manufacture_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_of_origin_id'], ['countries.id'], name=op.f('fk_items_country_of_origin_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['item_models.id'], name=op.f('fk_items_model_id_item_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['item_units.id'], name=op.f('fk_items_unit_id_item_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('code', name=op.f('uq_items_code'))
    )
    op.create_table('offices',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('office_type', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('division_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_offices_country_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_offices_district_id_districts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_offices_division_id_divisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offices')),
    sa.UniqueConstraint('code', name=op.f('uq_offices_code'))
    )
    op.create_table('upazilas',
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_upazilas_district_id_districts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upazilas')),
    sa.UniqueConstraint('district_id', 'name', name='uq_upazilas_district_name')
    )
    op.create_table('allocations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('allocation_type', sa.Enum('allocation', 'sanction', name='allocation_type'), nullable=False),
    sa.Column('fiscal_year_id', sa.BigInteger(), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_base_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'sent_back', 'cancelled', name='allocation_status'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_allocations_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_allocations_fiscal_year_id_fiscal_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_allocations_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ship_base_id'], ['ship_bases.id'], name=op.f('fk_allocations_ship_base_id_ship_bases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_allocations_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations')),
    sa.UniqueConstraint('code', name=op.f('uq_allocations_code'))
    )
    op.create_table('opening_stocks',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_opening_stocks_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_opening_stocks_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_stocks'))
    )
    op.create_table('stock_transactions',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('txn_type', sa.Enum('opening', 'allocation_out', 'receipt', 'adjustment', 'transfer_in', 'transfer_out', name='stock_txn_type'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('source', sa.Enum('procurement', 'from_ship', 'ex_bhatiary', 'manual', name='stock_source'), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_transactions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_stock_transactions_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stock_transactions_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transactions'))
    )
    op.create_table('stocks',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_stocks_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stocks_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('store_id', 'item_id', name='uq_stocks_store_item')
    )
    op.create_table('verifications',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('allocation_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'sent_back', name='verification_action'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], name=op.f('fk_verifications_allocation_id_allocations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_verifications_approver_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications')),
    sa.UniqueConstraint('code', name=op.f('uq_verifications_code'))
    )
    op.create_index(op.f('ix_verifications_allocation_id'), 'verifications', ['allocation_id'], unique=False)
    # deferred (cyclic) foreign keys
    op.create_foreign_key('fk_appointments_created_by_users', 'appointments', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_appointments_updated_by_users', 'appointments', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_brands_created_by_users', 'brands', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_brands_updated_by_users', 'brands', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_countries_created_by_users', 'countries', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_countries_updated_by_users', 'countries', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_divisions_created_by_users', 'divisions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_divisions_updated_by_users', 'divisions', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_categories_created_by_users', 'item_categories', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_categories_updated_by_users', 'item_categories', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_units_created_by_users', 'item_units', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_units_updated_by_users', 'item_units', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ranks_created_by_users', 'ranks', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ranks_updated_by_users', 'ranks', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_roles_created_by_users', 'roles', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_roles_updated_by_users', 'roles', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ship_base_categories_created_by_users', 'ship_base_categories', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ship_base_categories_updated_by_users', 'ship_base_categories', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_stores_created_by_users', 'stores', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_stores_updated_by_users', 'stores', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_created_by_users', 'users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_office_id_offices', 'users', 'offices', ['office_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_ship_base_id_ship_bases', 'users', 'ship_bases', ['ship_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_updated_by_users', 'users', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_districts_created_by_users', 'districts', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_districts_updated_by_users', 'districts', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_models_created_by_users', 'item_models', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_item_models_updated_by_users', 'item_models', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ship_bases_created_by_users', 'ship_bases', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ship_bases_updated_by_users', 'ship_bases', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_items_created_by_users', 'items', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_items_updated_by_users', 'items', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_offices_created_by_users', 'offices', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_offices_updated_by_users', 'offices', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_upazilas_created_by_users', 'upazilas', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_upazilas_updated_by_users', 'upazilas', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_allocations_created_by_users', 'allocations', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_allocations_updated_by_users', 'allocations', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_opening_stocks_created_by_users', 'opening_stocks', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_opening_stocks_updated_by_users', 'opening_stocks', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_verifications_created_by_users', 'verifications', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_verifications_updated_by_users', 'verifications', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_created_by_users', 'appointments', type_='foreignkey')
    op.drop_constraint('fk_appointments_updated_by_users', 'appointments', type_='foreignkey')
    op.drop_constraint('fk_brands_created_by_users', 'brands', type_='foreignkey')
    op.drop_constraint('fk_brands_updated_by_users', 'brands', type_='foreignkey')
    op.drop_constraint('fk_countries_created_by_users', 'countries', type_='foreignkey')
    op.drop_constraint('fk_countries_updated_by_users', 'countries', type_='foreignkey')
    op.drop_constraint('fk_divisions_created_by_users', 'divisions', type_='foreignkey')
    op.drop_constraint('fk_divisions_updated_by_users', 'divisions', type_='foreignkey')
    op.drop_constraint('fk_item_categories_created_by_users', 'item_categories', type_='foreignkey')
    op.drop_constraint('fk_item_categories_updated_by_users', 'item_categories', type_='foreignkey')
    op.drop_constraint('fk_item_units_created_by_users', 'item_units', type_='foreignkey')
    op.drop_constraint('fk_item_units_updated_by_users', 'item_units', type_='foreignkey')
    op.drop_constraint('fk_ranks_created_by_users', 'ranks', type_='foreignkey')
    op.drop_constraint('fk_ranks_updated_by_users', 'ranks', type_='foreignkey')
    op.drop_constraint('fk_roles_created_by_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_roles_updated_by_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_ship_base_categories_created_by_users', 'ship_base_categories', type_='foreignkey')
    op.drop_constraint('fk_ship_base_categories_updated_by_users', 'ship_base_categories', type_='foreignkey')
    op.drop_constraint('fk_stores_created_by_users', 'stores', type_='foreignkey')
    op.drop_constraint('fk_stores_updated_by_users', 'stores', type_='foreignkey')
    op.drop_constraint('fk_users_created_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_office_id_offices', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_ship_base_id_ship_bases', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_updated_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_districts_created_by_users', 'districts', type_='foreignkey')
    op.drop_constraint('fk_districts_updated_by_users', 'districts', type_='foreignkey')
    op.drop_constraint('fk_item_models_created_by_users', 'item_models', type_='foreignkey')
    op.drop_constraint('fk_item_models_updated_by_users', 'item_models', type_='foreignkey')
    op.drop_constraint('fk_ship_bases_created_by_users', 'ship_bases', type_='foreignkey')
    op.drop_constraint('fk_ship_bases_updated_by_users', 'ship_bases', type_='foreignkey')
    op.drop_constraint('fk_items_created_by_users', 'items', type_='foreignkey')
    op.drop_constraint('fk_items_updated_by_users', 'items', type_='foreignkey')
    op.drop_constraint('fk_offices_created_by_users', 'offices', type_='foreignkey')
    op.drop_constraint('fk_offices_updated_by_users', 'offices', type_='foreignkey')
    op.drop_constraint('fk_upazilas_created_by_users', 'upazilas', type_='foreignkey')
    op.drop_constraint('fk_upazilas_updated_by_users', 'upazilas', type_='foreignkey')
    op.drop_constraint('fk_allocations_created_by_users', 'allocations', type_='foreignkey')
    op.drop_constraint('fk_allocations_updated_by_users', 'allocations', type_='foreignkey')
    op.drop_constraint('fk_opening_stocks_created_by_users', 'opening_stocks', type_='foreignkey')
    op.drop_constraint('fk_opening_stocks_updated_by_users', 'opening_stocks', type_='foreignkey')
    op.drop_constraint('fk_verifications_created_by_users', 'verifications', type_='foreignkey')
    op.drop_constraint('fk_verifications_updated_by_users', 'verifications', type_='foreignkey')
    op.drop_index(op.f('ix_verifications_allocation_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('stocks')
    op.drop_table('stock_transactions')
    op.drop_table('opening_stocks')
    op.drop_table('allocations')
    op.drop_table('upazilas')
    op.drop_table('offices')
    op.drop_table('items')
    op.drop_table('ship_bases')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('item_models')
    op.drop_table('districts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('ship_base_categories')
    op.drop_table('roles')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_procurement_items_grn_no'), table_name='procurement_items')
    op.drop_table('procurement_items')
    op.drop_table('modules')
    op.drop_table('item_units')
    op.drop_table('item_categories')
    op.drop_table('fiscal_years')
    op.drop_table('divisions')
    op.drop_table('countries')
    op.drop_table('brands')
    op.drop_table('appointments')
    # drop enum types
    op.execute("DROP TYPE IF EXISTS status")
    op.execute("DROP TYPE IF EXISTS user_type")
    op.execute("DROP TYPE IF EXISTS ship_base_type")
    op.execute("DROP TYPE IF EXISTS allocation_type")
    op.execute("DROP TYPE IF EXISTS allocation_status")
    op.execute("DROP TYPE IF EXISTS verification_action")
    op.execute("DROP TYPE IF EXISTS stock_txn_type")
    op.execute("DROP TYPE IF EXISTS stock_source")
    op.execute("DROP TYPE IF EXISTS functional_status")
    # ### end Alembic commands ###